package com.jida.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jida.db.bean.Test;
import com.jida.db.bean.TestTeacher;
import com.jida.db.bean.TestUser;

import com.jida.db.greendao.TestDao;
import com.jida.db.greendao.TestTeacherDao;
import com.jida.db.greendao.TestUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig testTeacherDaoConfig;
    private final DaoConfig testUserDaoConfig;

    private final TestDao testDao;
    private final TestTeacherDao testTeacherDao;
    private final TestUserDao testUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        testTeacherDaoConfig = daoConfigMap.get(TestTeacherDao.class).clone();
        testTeacherDaoConfig.initIdentityScope(type);

        testUserDaoConfig = daoConfigMap.get(TestUserDao.class).clone();
        testUserDaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        testTeacherDao = new TestTeacherDao(testTeacherDaoConfig, this);
        testUserDao = new TestUserDao(testUserDaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(TestTeacher.class, testTeacherDao);
        registerDao(TestUser.class, testUserDao);
    }
    
    public void clear() {
        testDaoConfig.clearIdentityScope();
        testTeacherDaoConfig.clearIdentityScope();
        testUserDaoConfig.clearIdentityScope();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public TestTeacherDao getTestTeacherDao() {
        return testTeacherDao;
    }

    public TestUserDao getTestUserDao() {
        return testUserDao;
    }

}
